const router = require('express').Router()
const multer = require('multer')
const multerConfig = require('./config/multer')
const RecentlyRegistered = require('./controllers/RecentlyRegistered')
const LostPetController = require('./controllers/LostPetController')
const FoundPetController = require('./controllers/FoundPetController')
const RescuedPetController = require('./controllers/RescuedPetController')
const UserController = require('./controllers/UserController')
const AuthController = require('./controllers/AuthController')
const CertTest = require('./controllers/CertTest')
const AdsTxt = require('./controllers/AdsTxt')
// const authMiddleware = require('./middlewares/auth')

router.post('/user', UserController.store)
router.post('/user/facebook', UserController.facebookLogin)
router.post('/authenticate', AuthController.auth)
router.post('/forgot_password', AuthController.forgotPassword)
router.post('/reset_password', AuthController.resetPassword)

// router.use(authMiddleware)

router.get("/recently", RecentlyRegistered.index)
router.get("/rescued", RescuedPetController.index)
router.post("/rescued", multer(multerConfig).any('file'), RescuedPetController.store)
router.get("/lost", LostPetController.index)
router.get("/lost/:id", LostPetController.findOnePet)
router.post('/lost', multer(multerConfig).any('file'), LostPetController.store)
router.put("/lost/:id", multer(multerConfig).any('file'), LostPetController.update)
router.delete("/lost/:id", LostPetController.delete)
router.get("/found", FoundPetController.index)
router.get("/found/:id", FoundPetController.findOnePet)
router.post('/found', multer(multerConfig).any('file'), FoundPetController.store)
router.put("/found/:id", multer(multerConfig).any('file'), FoundPetController.update)
router.delete("/found/:id", FoundPetController.delete)
router.get("/user/lost/:id", UserController.findUserAndPopulateLost)
router.get("/user/found/:id", UserController.findUserAndPopulateFound)
router.get("/user/favorites/lost/:id", UserController.lostFavorites)
router.get("/user/favorites/found/:id", UserController.foundFavorites)
router.put("/user/notification/:id", UserController.updateNotification)
router.put("/user/lost/:id", UserController.updateLostFavorite)
router.put("/user/found/:id", UserController.updateFoundFavorite)
router.delete("/user/:id", UserController.delete)
router.put('/authenticate/:id', AuthController.updatePassword)
router.get('/.well-known/pki-validation/:name', CertTest.index)
router.get('/app-ads.txt', AdsTxt.index)

module.exports = router
